services:
  jenkins:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./src:/src
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      ADMIN_PASSWORD: admin
      CONF_DIR: /src/jobs
    networks:
      - jenkins_network

volumes:
  jenkins_home:
networks:
  jenkins_network:
    driver: bridge
