jenkins:
  systemMessage: "CasC test"
  securityRealm:
    local:
      allowsSignup: true
      users: # Ideally, you should use external user databases like LDAP
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true

unclassified:
  casCGlobalConfig:
    configurationPath: ${CASC_JENKINS_CONFIG}

jobs:
  - file: "${CONF_DIR}/test.groovy"
  - file: "${CONF_DIR}/with-file.groovy"
  - file: "${CONF_DIR}/docker.groovy"
  - file: "${CONF_DIR}/dockerfile.groovy"
